// Danh sách ngân hàng Việt Nam. `code` là giá trị lưu vào sepay_bank_info.bank_code — dùng đúng
// short name theo chuẩn VietQR/SePay (tham số `bank` của qr.sepay.vn). `fullName` để tìm kiếm.
export interface VnBank {
  code: string;
  shortName: string;
  fullName: string;
}

export const VN_BANKS: VnBank[] = [
  { code: "Vietcombank", shortName: "Vietcombank", fullName: "Ngân hàng TMCP Ngoại thương Việt Nam" },
  { code: "VietinBank", shortName: "VietinBank", fullName: "Ngân hàng TMCP Công thương Việt Nam" },
  { code: "BIDV", shortName: "BIDV", fullName: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam" },
  { code: "Agribank", shortName: "Agribank", fullName: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam" },
  { code: "Techcombank", shortName: "Techcombank", fullName: "Ngân hàng TMCP Kỹ thương Việt Nam" },
  { code: "MBBank", shortName: "MB Bank", fullName: "Ngân hàng TMCP Quân đội" },
  { code: "ACB", shortName: "ACB", fullName: "Ngân hàng TMCP Á Châu" },
  { code: "VPBank", shortName: "VPBank", fullName: "Ngân hàng TMCP Việt Nam Thịnh Vượng" },
  { code: "TPBank", shortName: "TPBank", fullName: "Ngân hàng TMCP Tiên Phong" },
  { code: "Sacombank", shortName: "Sacombank", fullName: "Ngân hàng TMCP Sài Gòn Thương Tín" },
  { code: "HDBank", shortName: "HDBank", fullName: "Ngân hàng TMCP Phát triển TP. Hồ Chí Minh" },
  { code: "VietCapitalBank", shortName: "Bản Việt (BVBank)", fullName: "Ngân hàng TMCP Bản Việt" },
  { code: "SCB", shortName: "SCB", fullName: "Ngân hàng TMCP Sài Gòn" },
  { code: "VIB", shortName: "VIB", fullName: "Ngân hàng TMCP Quốc tế Việt Nam" },
  { code: "SHB", shortName: "SHB", fullName: "Ngân hàng TMCP Sài Gòn - Hà Nội" },
  { code: "Eximbank", shortName: "Eximbank", fullName: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam" },
  { code: "MSB", shortName: "MSB", fullName: "Ngân hàng TMCP Hàng Hải" },
  { code: "SeABank", shortName: "SeABank", fullName: "Ngân hàng TMCP Đông Nam Á" },
  { code: "OCB", shortName: "OCB", fullName: "Ngân hàng TMCP Phương Đông" },
  { code: "LPBank", shortName: "LPBank", fullName: "Ngân hàng TMCP Lộc Phát Việt Nam (LienVietPostBank)" },
  { code: "BacABank", shortName: "Bac A Bank", fullName: "Ngân hàng TMCP Bắc Á" },
  { code: "PVcomBank", shortName: "PVcomBank", fullName: "Ngân hàng TMCP Đại Chúng Việt Nam" },
  { code: "NamABank", shortName: "Nam A Bank", fullName: "Ngân hàng TMCP Nam Á" },
  { code: "VietABank", shortName: "VietABank", fullName: "Ngân hàng TMCP Việt Á" },
  { code: "ABBANK", shortName: "ABBANK", fullName: "Ngân hàng TMCP An Bình" },
  { code: "NCB", shortName: "NCB", fullName: "Ngân hàng TMCP Quốc Dân" },
  { code: "PGBank", shortName: "PGBank", fullName: "Ngân hàng TMCP Xăng dầu Petrolimex" },
  { code: "Vietbank", shortName: "VietBank", fullName: "Ngân hàng TMCP Việt Nam Thương Tín" },
  { code: "BaoVietBank", shortName: "BaoViet Bank", fullName: "Ngân hàng TMCP Bảo Việt" },
  { code: "SaigonBank", shortName: "SaigonBank", fullName: "Ngân hàng TMCP Sài Gòn Công Thương" },
  { code: "KienLongBank", shortName: "KienLongBank", fullName: "Ngân hàng TMCP Kiên Long" },
  { code: "DongABank", shortName: "Đông Á (DongA Bank)", fullName: "Ngân hàng TMCP Đông Á" },
  { code: "CBBank", shortName: "CBBank", fullName: "Ngân hàng Xây dựng Việt Nam" },
  { code: "GPBank", shortName: "GPBank", fullName: "Ngân hàng Dầu khí Toàn cầu" },
  { code: "Oceanbank", shortName: "OceanBank", fullName: "Ngân hàng Đại Dương" },
  { code: "COOPBANK", shortName: "Co-op Bank", fullName: "Ngân hàng Hợp tác xã Việt Nam" },
  { code: "ShinhanBank", shortName: "Shinhan Bank", fullName: "Ngân hàng TNHH MTV Shinhan Việt Nam" },
  { code: "WooriBank", shortName: "Woori Bank", fullName: "Ngân hàng TNHH MTV Woori Việt Nam" },
  { code: "PublicBank", shortName: "Public Bank", fullName: "Ngân hàng TNHH MTV Public Việt Nam" },
  { code: "HongLeong", shortName: "Hong Leong", fullName: "Ngân hàng TNHH MTV Hong Leong Việt Nam" },
  { code: "HSBC", shortName: "HSBC", fullName: "Ngân hàng TNHH MTV HSBC Việt Nam" },
  { code: "StandardChartered", shortName: "Standard Chartered", fullName: "Ngân hàng TNHH MTV Standard Chartered Việt Nam" },
  { code: "IndovinaBank", shortName: "Indovina (IVB)", fullName: "Ngân hàng TNHH Indovina" },
  { code: "UOB", shortName: "UOB", fullName: "Ngân hàng TNHH MTV UOB Việt Nam" },
  { code: "CIMB", shortName: "CIMB", fullName: "Ngân hàng TNHH MTV CIMB Việt Nam" },
  { code: "VRB", shortName: "VRB", fullName: "Ngân hàng Liên doanh Việt - Nga" },
  { code: "Timo", shortName: "Timo", fullName: "Timo by Ban Viet Bank" },
  { code: "CAKE", shortName: "CAKE", fullName: "CAKE by VPBank" },
  { code: "Ubank", shortName: "Ubank", fullName: "Ubank by VPBank" },
  { code: "ViettelMoney", shortName: "Viettel Money", fullName: "Tổng công ty Dịch vụ số Viettel" },
  { code: "VNPTMoney", shortName: "VNPT Money", fullName: "VNPT Money" },
];
